version: '3.8'
services:
  backend:
    build: .
    container_name: shoppeclone-backend
    ports:
      - "8088:8088"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
      - redis
    networks:
      - shoppeclone-network

  redis:
    image: redis:alpine
    container_name: shoppeclone-redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - shoppeclone-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: shoppeclone-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Disable security for local development to avoid SSL/password config complexity
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - shoppeclone-network

volumes:
  elasticsearch-data:
  redis-data:

networks:
  shoppeclone-network:
    driver: bridge
